config/routes.rb
Zampr::Application.routes.draw do

  get "help/index"
  get "help/buy"
  get "help/sell"
  get "help/contact"
  get "help/members"
  get "help/community"
  get "help/fees"
  get "help/policies"
  get "help/security"

  devise_for :users
  resources :listings

  get "pages/about"
  get "pages/contact"
  get 'seller'  =>  "listings#seller"

  root 'listings#index'
  

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.png"
	else
		has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.png",
										:storage => :dropbox,
    								:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    								:path => ":style/:id_:filename"
  end

  validates :name, :description, :price, presence:true
  validates :price, numericality: { greater_than: 0 }
  validates_attachment_presence :image

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end

  def buy
  end

  def sell
  end

  def contact
  end

  def members
  end

  def community
  end

  def fees
  end

  def policies
  end

  def security
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image )
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing does not belong to you. Please sign in or sign up. Thanks"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/help/buy.html.erb
<h1>Help#buy</h1>
<p>Find me in app/views/help/buy.html.erb</p>

app/views/help/community.html.erb
<h1>Help#community</h1>
<p>Find me in app/views/help/community.html.erb</p>

app/views/help/contact.html.erb
<h1>Help#contact</h1>
<p>Find me in app/views/help/contact.html.erb</p>

app/views/help/fees.html.erb
<h1>Help#fees</h1>
<p>Find me in app/views/help/fees.html.erb</p>

app/views/help/index.html.erb
<div class="col-md-10 col-md-offset-1">
    <h2 class="orange">Help center</h2><hr>
</div>
    

<div class="row">
  <div class="col-md-2 col-md-offset-1">
     <ul>
      <p><%= link_to "About Zampr", pages_about_path %></p>           
      <p><%= link_to "Buy on Zampr", help_buy_path %></p>
      <p><%= link_to "Sell on Zampr", help_sell_path %></p>
      <p><%= link_to "Accounts & Memberships", help_members_path %></p>
      <p><%= link_to "Community", help_community_path %></p>
      <p><%= link_to "Policies", help_policies_path %></p>
      <p><%= link_to "Fees", help_fees_path %></p>
      <p><%= link_to "Security", help_security_path %></p>
      <p><%= link_to "Privacy", help_security_path %></p>
      <p><%= link_to "Contact", pages_contact_path %></p>
    </ul>
  </div>
</div>

app/views/help/members.html.erb
<h1>Help#members</h1>
<p>Find me in app/views/help/members.html.erb</p>

app/views/help/policies.html.erb
<h1>Help#policies</h1>
<p>Find me in app/views/help/policies.html.erb</p>

app/views/help/security.html.erb
<h1>Help#security</h1>
<p>Find me in app/views/help/security.html.erb</p>

app/views/help/sell.html.erb
<h1>Help#sell</h1>
<p>Find me in app/views/help/sell.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer">
	<hr><h6 class="center">Copyright Zampr 2014
	 	| Blog 
	 	| <%= link_to "About", pages_about_path %>
	  | <%= link_to "Contact", pages_contact_path %>
	  | <%= link_to "Press", help_buy_path %>
	  | <%= link_to "Privacy", help_community_path %>
	  | <%= link_to "Policies", help_policies_path %> 
	  | <%= link_to "Buyers", help_buy_path %>
	  | <%= link_to "Sellers", help_sell_path %>
	  | <%= link_to "Help", help_index_path %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
      <%= link_to "Zampr", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">              
              <li><%= link_to "My Listings", seller_path %></li>
              <li><%= link_to "New Listing", new_listing_path %></li>
              <li><a href="#">Community</a></li>
              <li><a href="#">Messages</a></li>              
              <li class="divider"></li>
              <li><%= link_to "My Profile", edit_user_registration_path %></li>
              <li><%= link_to "Help", help_index_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>           
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Search", new_user_registration_path %></li>           
          <li><%= link_to "Join Free", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Zampr</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= render 'layouts/header' %>

		<div class="container">
			<% flash.each do |name, msg| %>
   		 <% if msg.is_a?(String) %>
    	 	 <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
      		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    		    <%= content_tag :div, msg, :id => "flash_#{name}" %>
   		   </div>
  		  <% end %>
		  <% end %>
			<%= yield %>		
		</div>
		
		<%= render 'layouts/footer' %>
	
	</body> 	
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">     
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name your new item" %>
  </div> 

  <div class="form-group desc">
    <%= f.text_area :description, class: "form-control", placeholder: "Enter a description" %>
  </div>

  <div class="form-group">
    <%= f.text_field :price, class: "form-control", placeholder: "Price" %>
  </div><br>

  <div class="row center">
    <div class="col-md-6 col-md-offset-3">
      <div>
        <%= f.file_field :image %><br>
      </div>
      <div>
        <%= f.submit "Update", class: "btn btn-primary btn-block" %><br>
      </div>

      
    </div>
  </div>

<% end %>
  

app/views/listings/edit.html.erb
<div class="row center">
	<div class="col-md-4 col-md-offset-4">
		<h1>Editing listing</h1><hr>

		<%= render 'form' %>		

		<%= link_to 'Show', @listing, class: "btn btn-link" %> |
		<%= link_to 'Back', listings_path, class: "btn btn-link" %>
	</div>
</div>

app/views/listings/index.html.erb
<div>
  <h3>Featured</h3><br><hr><br>
</div>

<div class="row">    
  <% @listings.each do |listing| %>
    <div class="col-md-2">      
      <div class="thumbnail">
        <%= link_to image_tag(listing.image.url), listing %>
        <div class="caption">
          <h3><%= listing.name %></h3>
          <p><%= number_to_currency(listing.price) %></p>
          <h6><%= "Sold by #{listing.user.name}" %></h6>                
        </div>
      </div>
    </div>      
  <% end %>
</div>
  
<div class="col-md-offset-10">
  <h6>Find more featured gifts here</h6>
</div>

<hr>     

<% if user_signed_in? %>
    <%= link_to 'New Listing', new_listing_path %>
<% end %>

app/views/listings/new.html.erb
<div class="row center">
	<div class="col-md-4 col-md-offset-4">
		<h3>Create a new Zampr</h3><hr>

		<%= render 'form' %>

				<%= link_to 'Back', listings_path %>
	</div>
</div>

app/views/listings/seller.html.erb
<br>
<div class="row">
  <div class="col-md-2">
    <table>        
      <p class="menu"><%= link_to "My Profile", edit_user_registration_path %></p><hr>
      <p class="menu"><%= link_to "Community", help_index_path %></p><hr>
      <p class="menu"><%= link_to "Messages", destroy_user_session_path, method: :delete %></p><hr>
      <p class="menu"><%= link_to "New Listing", new_listing_path %></p><hr>
      <p class="menu"><%= link_to "Help", help_index_path %></p><hr>
      <p class="menu"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></p><hr>
    </table>
  </div>

  <div class="col-md-10">
    <table class="table table-striped table-bordered">
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>        
        <th>Action</th>
      </tr>

      <% @listings.each do |listing| %>
        <tr>
          <td class="center"><%= image_tag listing.image.url(:thumb) %></td>
          <td><%= listing.name %></td>
          <td><%= listing.description %></td>
          <td><%= number_to_currency(listing.price) %></td>
          <td class="center">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                Action <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "View Listings", listing, class: "btn btn-link" %></li>
                <li><%= link_to "Edit Listings", edit_listing_path(listing), class: "btn btn-link" %></li>
                <li><%= link_to "Delete Listing", listing, method: :delete, data: {confirm: "Are you suyre?" }, class: "btn btn-link" %></li>
              </ul>
            </div>      
          </td>
       </tr>
      <% end %>
    </table>
  </div>
</div>

<br><br><br><br>

app/views/listings/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<div class="thumbnail">
				<%= image_tag @listing.image.url %>
			</div>
		</div>

		<div class="col-md-4">
			<h3><%= @listing.name %></h3>
			<h4><%= number_to_currency(@listing.price) %></h4>
			<p><%= @listing.description %></p>
			<%= link_to 'Back', root_path %>
			<% if current_user == @listing.user %>
			| <%= link_to 'Edit', edit_listing_path(@listing) %>
			|	<%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
				
		</div>
	</div>
</div>


		

app/views/pages/about.html.erb
<h4>Welcome to Zampr</h4>

<p></p>
<p>Zampr is an online marketplace where you can buy and sell hampers, gift boxes and kits for any occassion</p>
<p>For those times when you know what to say but don't have the words you can say it with a gift from Zampr</p>

app/views/pages/contact.html.erb
<h4>General Enquiries</h4>
<p>Email us at contact@zampr.com</p>

<h4>Account Enquiries</h4>
<p>Email us at accounts@zampr.com</p>

<h4>Buyer Enquiries</h4>
<p>Email us at buyer@zampr.com</p>

<h4>Seller Enquiries</h4>
<p>Email us at seller@zampr.com</p>

<h4>Ask us a question</h4>
<p>Email us at faqs@zampr.com</p>